blank_issues_enabled: false
contact_links:
  - name: "Windows Feedback Hub for end-user feedback"
    url: http://aka.ms
    about: If you have issues and feedback on the subsystem for non-developer topics, please use Windows Feedback Hub
 
